### PR TITLE
Referral Create and edit pages - Fixes to decision boxes, UI changes (not completed)

### PR DESCRIPTION
**Pull request by FulfordD**
Hope this is working now, let me know if you come across any issues. Will continue to work on the UI later today

### CODE REVIEW

**Comment by snowy2651** [comment]
Its good for tomorrow's meeting, but just a couple of things, when first accessing the screen, both the Suitable and Not Suitable comment boxes display., Also, can we change the message if not decision button selected to 'Decision Required'. On the edit screen, we need to display the highest priority status, but as display only.

**Comment by FulfordD** [comment]
You haven't merged it in yet!

**Comment by snowy2651** [comment]
Im so confused! I thought I was picking it up from FulfordD, not merging it in! Shoot me if im being thick! I think we keep misunderstanding each other!

**Comment by FulfordD** [comment]
Shall I do it this time?

**Comment by snowy2651** [comment]
All Good!

**Pull request merged**
